<?php
/*
*   PD box sizes for Satchels ( < 5KG ) and Envelopes
****************************************************************************
*   These dimensions are obtained from the Australia Post. For some of the Satchels,
*   the height is provided by the comparing short girth of the item
*   with satchel_width_allawance and long girth of the item with satchel_length_allawance
*   Satchel girth
*   1) ((Satchel Width x 2) - 1)
*   2) ((Satchel Length x 2) - 1)
*   Package Girth
*   1) (Shortest + Mid Dimension)*2
*   2) (Shortest + Longest Dimension)*2
*   Package Girth <= Satchel girth
****************************************************************************
*/
return array(
	//Satchels
	'500g satchel (EP) (PP)'    =>  array(
		'order'         => 1,
		'name'          => '500g satchel (EP) (PP)',
		'outer_length'  => 22,
		'outer_width'   => 35.5,
		'outer_height'  => 5,
		'inner_length'  => 22,
		'inner_width'   => 35.5,
		'inner_height'  => 5,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'1kg satchel (EP) (PP)'     =>  array(
		'order'         => 2,
		'name'          => '1kg satchel (EP) (PP)',
		'outer_length'  => 26.5,
		'outer_width'   => 38.5,
		'outer_height'  => 5,
		'inner_length'  => 26.5,
		'inner_width'   => 38.5,
		'inner_height'  => 5,
		'box_weight'    => 0,
		'max_weight'    => 1,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'3kg satchel (EP) (PP)'     =>  array(
		'order'         => 3,
		'name'          => '3kg satchel (EP) (PP)',
		'outer_length'  => 31,
		'outer_width'   => 40.5,
		'outer_height'  => 5,
		'inner_length'  => 31,
		'inner_width'   => 40.5,
		'inner_height'  => 5,
		'box_weight'    => 0,
		'max_weight'    => 3,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'5kg satchel (EP) (PP)'     =>  array(
		'order'         => 4,
		'name'          => '5kg satchel (EP) (PP)',
		'outer_length'  => 43.5,
		'outer_width'   => 51,
		'outer_height'  => 5,
		'inner_length'  => 43.5,
		'inner_width'   => 51,
		'inner_height'  => 5,
		'box_weight'    => 0,
		'max_weight'    => 5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Small satchel (IE) (IS)'   =>  array(
		'order'         => 5,
		'name'          => 'Small satchel (IE) (IS)',
		'outer_length'  => 22,
		'outer_width'   => 35.3,
		'outer_height'  => 5,
		'inner_length'  => 22,
		'inner_width'   => 35.3,
		'inner_height'  => 5,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'International'
	),
	'Medium satchel (IE) (IS)'  =>  array(
		'order'         => 6,
		'name'          => 'Medium satchel (IE) (IS)',
		'outer_length'  => 26.5,
		'outer_width'   => 38,
		'outer_height'  => 5,
		'inner_length'  => 26.5,
		'inner_width'   => 38,
		'inner_height'  => 5,
		'box_weight'    => 0,
		'max_weight'    => 1,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'International'
	),
	'Large satchel (IE) (IS)'   =>  array(
		'order'         => 7,
		'name'          => 'Large satchel (IE) (IS)',
		'outer_length'  => 31,
		'outer_width'   => 40.5,
		'outer_height'  => 5,
		'inner_length'  => 31,
		'inner_width'   => 40.5,
		'inner_height'  => 5,
		'box_weight'    => 0,
		'max_weight'    => 2,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'International'
	),
	//Envelopes
	'DL Envelopes (EP)(WF)'     =>  array(
		'order'         => 8,
		'name'          => 'DL Envelopes (EP)(WF)',
		'outer_length'  => 11,
		'outer_width'   => 22,
		'outer_height'  => 2,
		'inner_length'  => 11,
		'inner_width'   => 22,
		'inner_height'  => 2,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'C5 Envelopes (EP) (RP)'    =>  array(
		'order'         => 9,
		'name'          => 'C5 Envelopes (EP) (RP)',
		'outer_length'  => 16.2,
		'outer_width'   => 22.9,
		'outer_height'  => 2,
		'inner_length'  => 16.2,
		'inner_width'   => 22.9,
		'inner_height'  => 2,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'B4 Envelopes (EP) (RP)'    =>  array(
		'order'         => 10,
		'name'          => 'B4 Envelopes (EP) (RP)',
		'outer_length'  => 25,
		'outer_width'   => 35.3,
		'outer_height'  => 2,
		'inner_length'  => 25,
		'inner_width'   => 35.3,
		'inner_height'  => 2,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'DL Envelopes (RWF)(R)'     =>  array(
		'order'         => 11,
		'name'          => 'DL Envelopes (RWF)(R)',
		'outer_length'  => 11,
		'outer_width'   => 22,
		'outer_height'  => 0.05,
		'inner_length'  => 11,
		'inner_width'   => 22,
		'inner_height'  => 0.05,
		'box_weight'    => 0,
		'max_weight'    => 0.25,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'C4 Envelopes'              =>  array(
		'order'         => 12,
		'name'          => 'C4 Envelopes',
		'outer_length'  => 32.4,
		'outer_width'   => 22.9,
		'outer_height'  => 2,
		'inner_length'  => 32.4,
		'inner_width'   => 22.9,
		'inner_height'  => 2,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'B4 envelopes (R)'          =>  array(
		'order'         => 13,
		'name'          => 'B4 envelopes (R)',
		'outer_length'  => 35.3,
		'outer_width'   => 25,
		'outer_height'  => 2,
		'inner_length'  => 35.3,
		'inner_width'   => 25,
		'inner_height'  => 2,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Postcards (RWF)'           =>  array(
		'order'         => 14,
		'name'          => 'Postcards (RWF)',
		'outer_length'  => 14.5,
		'outer_width'   => 10.5,
		'outer_height'  => 0.1,
		'inner_length'  => 14.5,
		'inner_width'   => 10.5,
		'inner_height'  => 0.1,
		'box_weight'    => 0,
		'max_weight'    => 0.1,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'DL Envelopes (RP)'         =>  array(
		'order'         => 15,
		'name'          => 'DL Envelopes (RP)',
		'outer_length'  => 13,
		'outer_width'   => 24,
		'outer_height'  => 0.5,
		'inner_length'  => 13,
		'inner_width'   => 24,
		'inner_height'  => 0.5,
		'box_weight'    => 0,
		'max_weight'    => 0.25,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Envelope (IE)'            =>  array(
		'order'         => 16,
		'name'          => 'Envelope (IE)',
		'outer_length'  => 29,
		'outer_width'   => 39,
		'outer_height'  => 0.5,
		'inner_length'  => 29,
		'inner_width'   => 39,
		'inner_height'  => 0.5,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'International'
	),
	'DL Envelopes (IE)'        =>  array(
		'order'         => 17,
		'name'          => 'DL Envelopes (IE)',
		'outer_length'  => 11,
		'outer_width'   => 22,
		'outer_height'  => 0.5,
		'inner_length'  => 11,
		'inner_width'   => 22,
		'inner_height'  => 0.5,
		'box_weight'    => 0,
		'max_weight'    => 0.05,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'International'
	),
	'C4 Envelopes (IE)'        =>   array(
		'order'         => 18,
		'name'          => 'C4 Envelopes (IE)',
		'outer_length'  => 22.9,
		'outer_width'   => 32.4,
		'outer_height'  => 0.5,
		'inner_length'  => 22.9,
		'inner_width'   => 32.4,
		'inner_height'  => 0.5,
		'box_weight'    => 0,
		'max_weight'    => 0.25,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'International'
	),
	'DL Envelopes (RPI)'       =>  array(
		'order'         => 19,
		'name'          => 'DL Envelopes (RPI)',
		'outer_length'  => 13,
		'outer_width'   => 24,
		'outer_height'  => 0.5,
		'inner_length'  => 13,
		'inner_width'   => 24,
		'inner_height'  => 0.5,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'International'
	),
	'B4 Envelopes (RPI)'       =>  array(
		'order'         => 20,
		'name'          => 'B4 Envelopes (RPI)',
		'outer_length'  => 25,
		'outer_width'   => 35.3,
		'outer_height'  => 0.5,
		'inner_length'  => 25,
		'inner_width'   => 35.3,
		'inner_height'  => 0.5,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'International'
	),
	'Jiffy® ShurTuff® Satchel (Size 1)'       =>  array(
		'order'         => 21,
		'name'          => 'Jiffy® ShurTuff® Satchel (Size 1)',
		'outer_length'  => 19,
		'outer_width'   => 26,
		'outer_height'  => 10,
		'inner_length'  => 19,
		'inner_width'   => 26,
		'inner_height'  => 10,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Jiffy® Shurtuff® Satchel (Size 2)'       =>  array(
		'order'         => 22,
		'name'          => 'Jiffy® Shurtuff® Satchel (Size 2)',
		'outer_length'  => 25,
		'outer_width'   => 32.5,
		'outer_height'  => 10,
		'inner_length'  => 25,
		'inner_width'   => 32.5,
		'inner_height'  => 10,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Jiffy® ShurTuff® Satchel (Size 3)'       =>  array(
		'order'         => 23,
		'name'          => 'Jiffy® ShurTuff® Satchel (Size 3)',
		'outer_length'  => 28,
		'outer_width'   => 38,
		'outer_height'  => 10,
		'inner_length'  => 28,
		'inner_width'   => 38,
		'inner_height'  => 10,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Jiffy® ShurTuff® Satchel (Size 4)'       =>  array(
		'order'         => 24,
		'name'          => 'Jiffy® ShurTuff® Satchel (Size 4)',
		'outer_length'  => 34,
		'outer_width'   => 44,
		'outer_height'  => 10,
		'inner_length'  => 34,
		'inner_width'   => 44,
		'inner_height'  => 10,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Jiffy® ShurTuff® Satchel (Size 5)'       =>  array(
		'order'         => 25,
		'name'          => 'Jiffy® ShurTuff® Satchel (Size 5)',
		'outer_length'  => 42,
		'outer_width'   => 45,
		'outer_height'  => 10,
		'inner_length'  => 42,
		'inner_width'   => 45,
		'inner_height'  => 10,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Jiffy® ShurTuff® Satchel (Size 6)'       =>  array(
		'order'         => 26,
		'name'          => 'Jiffy® ShurTuff® Satchel (Size 6)',
		'outer_length'  => 60,
		'outer_width'   => 65,
		'outer_height'  => 10,
		'inner_length'  => 60,
		'inner_width'   => 65,
		'inner_height'  => 10,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => true,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Mailing box, Bx1'       =>  array(
		'order'         => 27,
		'name'          => 'Mailing box, Bx1',
		'outer_length'  => 22,
		'outer_width'   => 16,
		'outer_height'  => 77,
		'inner_length'  => 22,
		'inner_width'   => 16,
		'inner_height'  => 77,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Mailing box, Bx2'       =>  array(
		'order'         => 28,
		'name'          => 'Mailing box, Bx2',
		'outer_length'  => 31,
		'outer_width'   => 22.5,
		'outer_height'  => 10.2,
		'inner_length'  => 31,
		'inner_width'   => 22.5,
		'inner_height'  => 10.2,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Mailing box, Bx3'       =>  array(
		'order'         => 29,
		'name'          => 'Mailing box, Bx3',
		'outer_length'  => 40,
		'outer_width'   => 20,
		'outer_height'  => 18,
		'inner_length'  => 40,
		'inner_width'   => 20,
		'inner_height'  => 18,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Mailing box, Bx4'       =>  array(
		'order'         => 30,
		'name'          => 'Mailing box, Bx4',
		'outer_length'  => 43,
		'outer_width'   => 30.5,
		'outer_height'  => 14,
		'inner_length'  => 43,
		'inner_width'   => 30.5,
		'inner_height'  => 14,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Mailing box, Bx5'       =>  array(
		'order'         => 31,
		'name'          => 'Mailing box, Bx5',
		'outer_length'  => 40.5,
		'outer_width'   => 30,
		'outer_height'  => 25.5,
		'inner_length'  => 40.5,
		'inner_width'   => 30,
		'inner_height'  => 25.5,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Mailing box, Bx18'       =>  array(
		'order'         => 32,
		'name'          => 'Mailing box, Bx18',
		'outer_length'  => 18,
		'outer_width'   => 18,
		'outer_height'  => 18,
		'inner_length'  => 18,
		'inner_width'   => 18,
		'inner_height'  => 18,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Mailing box, Bx19'       =>  array(
		'order'         => 33,
		'name'          => 'Mailing box, Bx19',
		'outer_length'  => 38.5,
		'outer_width'   => 28,
		'outer_height'  => 70,
		'inner_length'  => 38.5,
		'inner_width'   => 28,
		'inner_height'  => 70,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Mailing box, Bx20'       =>  array(
		'order'         => 34,
		'name'          => 'Mailing box, Bx20',
		'outer_length'  => 35,
		'outer_width'   => 50,
		'outer_height'  => 44,
		'inner_length'  => 35,
		'inner_width'   => 55,
		'inner_height'  => 44,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
	'Video/DVD, Bx6'       =>  array(
		'order'         => 30,
		'name'          => 'Video/DVD, Bx6',
		'outer_length'  => 22,
		'outer_width'   => 14.5,
		'outer_height'  => 35,
		'inner_length'  => 22,
		'inner_width'   => 14.5,
		'inner_height'  => 35,
		'box_weight'    => 0,
		'max_weight'    => 0.5,
		'is_enabled'    => false,
		'is_letter'     => false,
		'pack_type'     => 'PD',//Pre-defined
		'eligible_for'  => 'Domestic'
	),
);
